import subprocess
import json
import os
from strands import tool


# -------------------------
# RUNNER FUNCTION
# -------------------------
def run_semgrep_scan(repo_path: str, output_file: str) -> dict | None:
    try:
        if os.path.exists(output_file):
            os.remove(output_file)

        subprocess.run(
            [
                "semgrep",
                "scan",
                "--config", "auto",
                "--json",
                "-o", output_file,
                "--max-target-bytes", "50000000",
                repo_path
            ],
            check=True,
            capture_output=True,
            timeout=250
        )

        return None  # success

    except subprocess.TimeoutExpired:
        return {"error": "Timeout during Semgrep execution"}

    except subprocess.CalledProcessError as e:
        if os.path.exists(output_file):
            try:
                with open(output_file, encoding="utf-8") as f:
                    full_data = json.load(f)
            except Exception:
                full_data = {}

            return {
                "error": "Semgrep execution failed",
                "semgrep_errors": full_data.get("errors", []),
                "repo_path": repo_path
            }

        return {
            "error": "Semgrep execution failed",
            "details": (e.stderr or b"").decode(),
            "repo_path": repo_path
        }


# -------------------------
# PARSER FUNCTION
# -------------------------
def parse_semgrep_report(output_file: str) -> dict:
    if not os.path.exists(output_file):
        return {"error": "Report file was not generated."}

    try:
        with open(output_file, 'r', encoding='utf-8') as f:
            content = f.read().strip()
            full_data = json.loads(content) if content else {"results": [], "errors": []}
    except json.JSONDecodeError:
        return {"error": "Invalid JSON file generated by Semgrep"}

    findings_for_agent = []

    for item in full_data.get("results", []):
        extra = item.get("extra", {})
        severity = extra.get("severity", "UNKNOWN")

        if severity != "ERROR":
            continue

        metadata = extra.get("metadata", {})
        owasp_list = metadata.get("owasp", [])

        if not owasp_list:
            continue

        finding = {
            "rule_id": item.get("check_id"),
            "path": item.get("path"),
            "line": item.get("start", {}).get("line") or -1,
            "description": extra.get("message", ""),
            "severity": severity,
            "owasp_category": ", ".join(owasp_list),
            "remediation": None
        }

        findings_for_agent.append(finding)

    scan_errors = [
        {
            "type": err.get("type"),
            "file": err.get("path"),
            "message": err.get("message")
        }
        for err in full_data.get("errors", [])
    ]

    return {
        "findings_to_analyze": findings_for_agent,
        "scan_errors": scan_errors[:10],
        "full_report_path": output_file
    }


# -------------------------
# STRANDS AGENT TOOL
# -------------------------
@tool
def run_semgrep(repo_path: str) -> dict:
    """
    Run Semgrep scan on a repository and return summarized findings.
    """

    output_file = "raw_semgrep_report.json"

    error = run_semgrep_scan(repo_path, output_file)
    if error:
        return error

    return parse_semgrep_report(output_file)