import subprocess
import json
import os
from strands import tool


# -------------------------
# DEDUPLICATION HELPER
# -------------------------
def dedupe(findings):
    seen = set()
    result = []
    for f in findings:
        key = (
            f["path"],
            f["line"],
            f["rule_id"],
            f["severity"]
        )
        if key not in seen:
            seen.add(key)
            result.append(f)
    return result

# -------------------------
# SMALLER DESCRIPTIONS
# HELPER
# -------------------------
def extract_first_sentences(text: str, max_sentences: int = 2) -> str:
    if not text:
        return ""

    sentences = text.split(".")
    
    selected = [s.strip() for s in sentences if s.strip()][:max_sentences]

    if not selected:
        return ""

    return ". ".join(selected) + "."


# -------------------------
# RUNNER FUNCTION
# -------------------------
def run_semgrep_scan(repo_path: str, output_file: str) -> dict | None:
    try:
        if os.path.exists(output_file):
            os.remove(output_file)

        subprocess.run(
            [
                "semgrep",
                "scan",
                "--config", "auto",
                "--json",
                "-o", output_file,
                "--max-target-bytes", "50000000",
                repo_path
            ],
            check=True,
            capture_output=True,
            timeout=250
        )

        return None

    except subprocess.TimeoutExpired:
        return {"error": "Timeout during Semgrep execution"}

    except subprocess.CalledProcessError as e:
        if os.path.exists(output_file):
            try:
                with open(output_file, encoding="utf-8") as f:
                    full_data = json.load(f)
            except Exception:
                full_data = {}

            return {
                "error": "Semgrep execution failed",
                "semgrep_errors": full_data.get("errors", []),
                "repo_path": repo_path
            }

        return {
            "error": "Semgrep execution failed",
            "details": (e.stderr or b"").decode(),
            "repo_path": repo_path
        }


# -------------------------
# PARSER FUNCTION
# -------------------------
def parse_semgrep_report(output_file: str) -> dict:
    if not os.path.exists(output_file):
        return {"error": "Report file was not generated."}

    try:
        with open(output_file, 'r', encoding='utf-8') as f:
            content = f.read().strip()
            full_data = json.loads(content) if content else {"results": [], "errors": []}
    except json.JSONDecodeError:
        return {"error": "Invalid JSON file generated by Semgrep"}

    error_findings = []
    warning_findings= []

    for item in full_data.get("results", []):
        extra = item.get("extra", {})
        severity = extra.get("severity", "UNKNOWN")
 
        metadata = extra.get("metadata", {})
        owasp_list = metadata.get("owasp", [])

        if not owasp_list:
            continue

        finding = {
            "rule_id": item.get("check_id"),
            "path": item.get("path"),
            "line": item.get("start", {}).get("line") or -1,
            "description": extract_first_sentences(extra.get("message", "")),
            "severity": severity,
            "owasp_category": ", ".join(owasp_list),
            "remediation": None
        }

        if severity == "ERROR":
            error_findings.append(finding)
        elif severity == "WARNING":
            warning_findings.append(finding)

    error_findings = dedupe(error_findings)
    warning_findings = dedupe(warning_findings)

    findings_for_agent = []

    if len(error_findings) >= 5:
        findings_for_agent = error_findings[:10]

    elif len(error_findings) > 0:
        needed = 5 - len(error_findings)
        findings_for_agent = error_findings + warning_findings[:needed]

    else:
        findings_for_agent = warning_findings[:5]

    return {
        "findings_to_analyze": findings_for_agent,
    }


# -------------------------
# STRANDS AGENT TOOL
# -------------------------
@tool
def run_semgrep(repo_path: str) -> dict:
    """
    Run a Semgrep static analysis scan on a repository to detect OWASP Top 10 vulnerabilities.

    When to use:
    - Use this tool when you need to identify OWASP Top 10 vulnerabilities in source code.
    - Especially useful for detecting injection issues, insecure patterns, and misconfigurations.

    Args:
        repo_path (str): Absolute path to the repository to analyze.

    Returns:
        dict: A structured result containing:
            - "status": "success" or "error"
            - "findings_to_analyze": list of detected issues with:
                "rule_id": id of the rule used for the finding,
                "path": path of the finding,
                "line": starting line of the finding,
                "description": description of the finding,
                "severity": severity of the finding (should always be "ERROR" or "WARNING"),
                "owasp_category": list of owasp categories found,
                "remediation": Empty field you have to fill
            - "errors": list of errors (empty list on success, execution or parsing error on failure).
              Every error object always has exactly these three fields:
                "type": one of "SemgrepError", "SemgrepParseError", or a Semgrep internal type,
                "message": human-readable description of the error,
                "details": additional context string, or null if not available
    """

    output_file = "raw_semgrep_report.json"

    error = run_semgrep_scan(repo_path, output_file)
    if error:
        raw_details = error.get("details")
        semgrep_errors = error.get("semgrep_errors")
        if semgrep_errors:
            details = json.dumps(semgrep_errors)
        else:
            details = raw_details  

        return {
            "status": "error",
            "findings_to_analyze": [],
            "errors": [
                {
                    "type":      "SemgrepError",
                    "message":   error.get("error"),
                    "details":   details  
                }
            ],
        }

    result = parse_semgrep_report(output_file)

    if "error" in result:
        return {
            "status": "error",
            "findings_to_analyze": [],
            "errors": [
                {
                    "type":    "SemgrepParseError",
                    "message": result.get("error"),
                    "details": None
                }
            ],
        }

    return {
        "status": "success",
        "findings_to_analyze": result.get("findings_to_analyze", []),
        "errors": [],
    }
