import subprocess
import json
import os
from strands import tool


# -------------------------
# RUNNER FUNCTION
# -------------------------
def run_trivy_scan(repo_path: str, output_file: str) -> dict | None:
    try:
        if os.path.exists(output_file):
            os.remove(output_file)

        subprocess.run(
            [
                "trivy",
                "fs",
                repo_path,
                "--scanners", "secret",
                "--format", "json",
                "-o", output_file,
                "--quiet",
                "--no-progress"
            ],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            timeout=250
        )

        if not os.path.exists(output_file):
            return {
                "error": "Trivy did not generate output file",
                "repo_path": repo_path
            }

        if os.path.getsize(output_file) == 0:
            return {
                "error": "Trivy generated empty report",
                "repo_path": repo_path
            }

        return None

    except subprocess.TimeoutExpired:
        return {"error": "Timeout during Trivy execution"}

    except subprocess.CalledProcessError as e:
        return {
            "error": "Trivy execution failed",
            "details": (e.stderr or b"").decode(),
            "repo_path": repo_path
        }
    

# -------------------------
# PARSER FUNCTION
# -------------------------
def parse_trivy_report(output_file: str) -> dict:
    if not os.path.exists(output_file):
        return {"error": "Report file was not generated."}

    try:
        with open(output_file, 'r', encoding='utf-8') as f:
            content = f.read().strip()
            full_data = json.loads(content) if content else {"Results": []}
    except json.JSONDecodeError:
        return {"error": "Invalid JSON file generated by Trivy"}

    findings_for_agent = []

    for item in full_data.get("Results", []):
        target = item.get("Target") or "unknown"

        if item.get("Class") != "secret":
            continue

        secrets = item.get("Secrets") or []
        if not secrets:
            continue

        for secret in item.get("Secrets", []):
            
            if secret.get("Severity") not in {"HIGH", "CRITICAL"}:
                continue

            finding = {
                "rule_id": secret.get("RuleID"),
                "path": target or "unknown",
                "line": secret.get("StartLine", -1),
                "description": (secret.get("Title") or secret.get("RuleID") or "")[:200],
                "severity": secret.get("Severity"),
                "category": secret.get("Category"),
                "remediation": None
            }

            findings_for_agent.append(finding)

    seen = set()
    deduped = []

    for f in findings_for_agent:
        key = (f["path"], f["line"], f["rule_id"])
        if key not in seen:
            seen.add(key)
            deduped.append(f)

    findings_for_agent = deduped

    return {
        "findings_to_analyze": findings_for_agent,
        "full_report_path": output_file
    }

# -------------------------
# STRANDS AGENT TOOL
# -------------------------
@tool
def run_trivy(repo_path: str) -> dict:
    """
    Run Trivy scan on a repository and return summarized findings.
    """

    output_file = "raw_trivy_report.json"

    error = run_trivy_scan(repo_path, output_file)
    if error:
        return {
            "status": "error",
            "findings_to_analyze": [],
            "errors": [
                {
                    "type": "TrivyError",
                    "message": error.get("error"),
                    "details": error.get("details"),
                    "repo_path": error.get("repo_path")
                }
            ],
            "meta": {}
        }

    result = parse_trivy_report(output_file)

    if "error" in result:
        return {
            "status": "error",
            "findings_to_analyze": [],
            "errors": [
                {
                    "type": "TrivyParseError",
                    "message": result.get("error")
                }
            ],
            "meta": {}
        }

    return {
        "status": "success",
        "findings_to_analyze": result.get("findings_to_analyze", []),
        "errors": [],
        "meta": {
            "report_path": result.get("full_report_path")
        }
    }