import subprocess
import json
import os
from strands import tool


# -------------------------
# DEDUPLICATION HELPER
# -------------------------
def dedupe(findings):
    seen = set()
    result = []
    for f in findings:
        key = (f["path"], 
               f["line"], 
               f["rule_id"],
               f["severity"],
               )
        if key not in seen:
            seen.add(key)
            result.append(f)
    return result

# -------------------------
# RUNNER FUNCTION
# -------------------------
def run_trivy_scan(repo_path: str, output_file: str) -> dict | None:
    try:
        if os.path.exists(output_file):
            os.remove(output_file)

        subprocess.run(
            [
                "trivy",
                "fs",
                repo_path,
                "--scanners", "secret",
                "--format", "json",
                "-o", output_file,
                "--quiet",
                "--no-progress"
            ],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            timeout=250
        )

        if not os.path.exists(output_file):
            return {
                "error": "Trivy did not generate output file",
                "repo_path": repo_path
            }

        if os.path.getsize(output_file) == 0:
            return {
                "error": "Trivy generated empty report",
                "repo_path": repo_path
            }

        return None

    except subprocess.TimeoutExpired:
        return {"error": "Timeout during Trivy execution"}

    except subprocess.CalledProcessError as e:
        return {
            "error": "Trivy execution failed",
            "details": (e.stderr or b"").decode(),
            "repo_path": repo_path
        }


# -------------------------
# PARSER FUNCTION
# -------------------------
def parse_trivy_report(output_file: str) -> dict:
    if not os.path.exists(output_file):
        return {"error": "Report file was not generated."}

    try:
        with open(output_file, 'r', encoding='utf-8') as f:
            content = f.read().strip()
            full_data = json.loads(content) if content else {"Results": []}
    except json.JSONDecodeError:
        return {"error": "Invalid JSON file generated by Trivy"}

    critical_findings = []
    high_findings = []
    medium_findings = []

    for item in full_data.get("Results", []):
        target = item.get("Target") or "unknown"

        if item.get("Class") != "secret":
            continue

        secrets = item.get("Secrets") or []
        if not secrets:
            continue

        for secret in secrets: 
            severity = secret.get("Severity")
            if severity not in {"CRITICAL", "HIGH", "MEDIUM"}:
                continue

            finding = {
                "rule_id": secret.get("RuleID"),
                "path": target or "unknown",
                "line": secret.get("StartLine", -1),
                "description": (secret.get("Title") or secret.get("RuleID") or ""),
                "severity": severity,
                "secret_category": secret.get("Category"),
                "remediation": None
            }

            if severity == "CRITICAL":
                critical_findings.append(finding)
            elif severity == "HIGH":
                high_findings.append(finding)
            elif severity == "MEDIUM":
                medium_findings.append(finding)
    
    critical_findings = dedupe(critical_findings)
    high_findings = dedupe(high_findings)
    medium_findings = dedupe(medium_findings)

    findings_for_agent = []

    if len(critical_findings) >= 10:
        findings_for_agent = critical_findings[:10]

    elif len(critical_findings) > 0:
        needed = 10 - len(critical_findings)
        findings_for_agent = (
            critical_findings +
            high_findings[:needed]
        )

        if len(findings_for_agent) < 5:
            remaining = 5 - len(findings_for_agent)
            findings_for_agent += medium_findings[:remaining]

    elif len(high_findings) < 5:
        needed = 5 - len(high_findings)
        findings_for_agent = (
            high_findings + 
            medium_findings[:needed]
        )

    else:
        findings_for_agent = high_findings[:10]

    return {
        "findings_to_analyze": findings_for_agent
    }


# -------------------------
# STRANDS AGENT TOOL
# -------------------------
@tool
def run_trivy(repo_path: str) -> dict:
    """
    Run Trivy scan on a repository and return summarized secret findings.

    When to use:
    - Use this tool when you need to detect secrets in filesystem contents.
    - Especially useful for identifying high and critical severity secret leaks across repository files.

    Args:
        repo_path (str): Absolute path to the repository to scan.

    Returns:
        dict: A structured result containing:
            - "status": "success" or "error"
            - "findings_to_analyze": list of detected issues with:
                "rule_id": id of the secret rule,
                "path": path of the finding,
                "line": starting line of the finding,
                "description": description of the finding,
                "severity": severity of the finding,
                "category": category of the finding,
                "remediation": Empty field you have to fill
            - "errors": list of errors (empty list on success, execution or parsing error on failure).
              Every error object always has exactly these three fields:
                "type": one of "TrivyError", "TrivyParseError", or a Trivy internal type,
                "message": human-readable description of the error,
                "details": additional context string, or null if not available
    """

    output_file = "raw_trivy_report.json"

    error = run_trivy_scan(repo_path, output_file)
    if error:
        return {
            "status": "error",
            "findings_to_analyze": [],
            "errors": [
                {
                    "type": "TrivyError",
                    "message": error.get("error"),
                    "details": error.get("details")  
                }
            ],
        }

    result = parse_trivy_report(output_file)

    if "error" in result:
        return {
            "status": "error",
            "findings_to_analyze": [],
            "errors": [
                {
                    "type": "TrivyParseError",
                    "message": result.get("error"),
                    "details": None  
                }
            ],
        }

    return {
        "status": "success",
        "findings_to_analyze": result.get("findings_to_analyze", []),
        "errors": [],
    }
