FROM node:22-alpine AS builder

WORKDIR /app
COPY package*.json  ./
RUN npm ci

COPY src/analysis ./src/analysis
COPY src/app.module.ts ./src/
COPY src/main.ts ./src/

COPY tsconfig*.json ./
COPY nest-cli.json ./
RUN npm run build 

FROM node:22-alpine

RUN apk add --no-cache git curl

WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist

RUN npm ci --only=production && npm cache clean --force

EXPOSE 3001

CMD ["node", "dist/src/main"]