services:
  app:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.dev
    container_name: analysis
    ports:
      - '3000:3000'
    volumes:
      - ../../:/app
      - /app/node_modules
