import json
import os
from helpers.path_normalizer import normalize_path
from helpers.deduplicators.deduplicator_semgrep import dedupe
from helpers.smaller_description_semgrep import extract_first_sentences

def parse_semgrep_report(raw_report_path: str, repo_path: str) -> dict:
    if not os.path.exists(raw_report_path):
        return {
            "error": {
                "tool": "semgrep",
                "message":"Report file was not generated."
            }
        }

    try:
        with open(raw_report_path, 'r', encoding='utf-8') as f:
            content = f.read().strip()
            full_data = json.loads(content) if content else {"results": [], "errors": []}
    except json.JSONDecodeError:
        return {
            "error": {
                "tool": "semgrep",
                "message":"Invalid JSON file generated by Semgrep"
            }
        }  
    except Exception as e:
        return {
            "error": {
                "tool": "semgrep",
                "message": f"Unexpected error reading report: {str(e)}"
            }
        }

    all_findings = []

    for item in full_data.get("results", []):
        extra = item.get("extra", {}) 
        metadata = extra.get("metadata", {})
        owasp_list = metadata.get("owasp", [])
        raw_path = item.get("path", "")
        clean_path = normalize_path(raw_path, repo_path)

        if not owasp_list:
            continue

        severity = extra.get("severity", "UNKNOWN")

        finding = {
            "rule_id": item.get("check_id"),
            "path": clean_path,
            "line": item.get("start", {}).get("line") or -1,
            "description": extract_first_sentences(extra.get("message", "")),
            "severity": severity,
            "owasp_category": ", ".join(owasp_list),
            "remediation": None
        }

        all_findings.append(finding)
    all_findings = dedupe(all_findings)

    return {"raw_findings": all_findings}
