import json
import os

# -------------------------
# DEDUPLICATION HELPER
# -------------------------
def dedupe(findings):
    seen = set()
    result = []
    for f in findings:
        key = (f["path"], 
               f["line"], 
               f["rule_id"],
               f["severity"],
               )
        if key not in seen:
            seen.add(key)
            result.append(f)
    return result

# -------------------------
# PARSER FUNCTION
# -------------------------
def parse_trivy_report(raw_report_path: str) -> dict:
    if not os.path.exists(raw_report_path):
        return {"error": "Report file was not generated."}

    try:
        with open(raw_report_path, 'r', encoding='utf-8') as f:
            content = f.read().strip()
            full_data = json.loads(content) if content else {"Results": []}
    except json.JSONDecodeError:
        return {"error": "Invalid JSON file generated by Trivy"}

    all_findings = []

    for item in full_data.get("Results", []):
        target = item.get("Target") or "unknown"

        if item.get("Class") != "secret":
            continue

        secrets = item.get("Secrets") or []
        if not secrets:
            continue

        for secret in secrets: 
            severity = secret.get("Severity")
            
            finding = {
                "rule_id": secret.get("RuleID"),
                "path": target or "unknown",
                "line": secret.get("StartLine", -1),
                "description": (secret.get("Title") or secret.get("RuleID") or ""),
                "severity": severity,
                "secret_category": secret.get("Category"),
                "remediation": None
            }

            all_findings.append(finding)
    
    all_findings = dedupe(all_findings)

    return {
        "raw_findings": all_findings
    }