import json
import os
from helpers.deduplicators.deduplicator_trivy import dedupe

def parse_trivy_report(raw_report_path: str) -> dict:
    if not os.path.exists(raw_report_path):
        return {
            "error": {
                "tool": "trivy",
                "message": "Report file was not generated."
            }
        }

    try:
        with open(raw_report_path, 'r', encoding='utf-8') as f:
            content = f.read().strip()
            full_data = json.loads(content) if content else {"Results": []}
    except json.JSONDecodeError:
        return {
            "error": {
                "tool": "trivy",
                "message": "Invalid JSON file generated by Trivy."
            }
        }
    except Exception as e:
        return {
            "error": {
                "tool": "trivy",
                "message": f"Unexpected error reading Trivy report: {str(e)}"
            }
        }

    all_findings = []

    for item in full_data.get("Results", []):
        target = item.get("Target") or "unknown"

        if item.get("Class") != "secret":
            continue

        secrets = item.get("Secrets") or []
        if not secrets:
            continue

        for secret in secrets: 
            severity = secret.get("Severity")
            
            finding = {
                "rule_id": secret.get("RuleID"),
                "path": target or "unknown",
                "line": secret.get("StartLine", -1),
                "description": (secret.get("Title") or secret.get("RuleID") or ""),
                "severity": severity,
                "secret_category": secret.get("Category"),
                "remediation": None
            }

            all_findings.append(finding)
    
    all_findings = dedupe(all_findings)

    return {
        "raw_findings": all_findings
    }