import json
import os

# -------------------------
# DEDUPLICATION HELPER
# -------------------------
def dedupe(findings):
    seen = set()
    result = []
    for f in findings:
        key = (
            f["path"],
            f["line"],
            f["rule_id"],
            f["severity"]
        )
        if key not in seen:
            seen.add(key)
            result.append(f)
    return result

# -------------------------
# SMALLER DESCRIPTIONS
# HELPER
# -------------------------
def extract_first_sentences(text: str, max_sentences: int = 2) -> str:
    if not text:
        return ""

    sentences = text.split(".")
    
    selected = [s.strip() for s in sentences if s.strip()][:max_sentences]

    if not selected:
        return ""

    return ". ".join(selected) + "."

# ------------------------
# PARSER
# ------------------------
def parse_semgrep_report(raw_report_path: str) -> dict:
  if not os.path.exists(raw_report_path):
      return {"error": "Report file was not generated."}

  try:
      with open(raw_report_path, 'r', encoding='utf-8') as f:
          content = f.read().strip()
          full_data = json.loads(content) if content else {"results": [], "errors": []}
  except json.JSONDecodeError:
      return {"error": "Invalid JSON file generated by Semgrep"}

  all_findings = []

  for item in full_data.get("results", []):
      extra = item.get("extra", {}) 
      metadata = extra.get("metadata", {})
      owasp_list = metadata.get("owasp", [])

      if not owasp_list:
          continue

      severity = extra.get("severity", "UNKNOWN")

      finding = {
          "rule_id": item.get("check_id"),
          "path": item.get("path"),
          "line": item.get("start", {}).get("line") or -1,
          "description": extract_first_sentences(extra.get("message", "")),
          "severity": severity,
          "owasp_category": ", ".join(owasp_list),
          "remediation": None
      }

      all_findings.append(finding)
  all_findings = dedupe(all_findings)

  return {"raw_findings": all_findings}
