import sys
import types

mock_strands = types.ModuleType("strands")

def tool(func):
    return func

mock_strands.tool = tool

sys.modules["strands"] = mock_strands

import os
import json
import subprocess
from unittest.mock import patch
from src.agents.security.tools.trivy_functions import (
    parse_trivy_report,
    run_trivy_scan,
    run_trivy,
)

FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "fixtures")


def get_fixture_path(name):
    return os.path.join(FIXTURES_DIR, name)


# -------------------------
# PARSER TESTS
# -------------------------

def test_parser_valid():
    result = parse_trivy_report(get_fixture_path("trivy_valid.json"))

    assert len(result["findings_to_analyze"]) == 1
    finding = result["findings_to_analyze"][0]

    assert finding["rule_id"] == "private-key"
    assert finding["severity"] == "HIGH"
    assert finding["category"] == "AsymmetricPrivateKey"


def test_parser_empty():
    result = parse_trivy_report(get_fixture_path("trivy_empty.json"))

    assert result["findings_to_analyze"] == []


def test_parser_no_secrets():
    result = parse_trivy_report(get_fixture_path("trivy_no_secrets.json"))

    assert result["findings_to_analyze"] == []


def test_parser_low_severity_filtered():
    result = parse_trivy_report(get_fixture_path("trivy_low_severity.json"))

    assert result["findings_to_analyze"] == []


def test_parser_file_not_found():
    result = parse_trivy_report("nonexistent.json")

    assert "error" in result


def test_parser_invalid_json(tmp_path):
    file = tmp_path / "bad.json"
    file.write_text("not json")

    result = parse_trivy_report(str(file))

    assert "error" in result

def test_parser_skips_non_secret_class(tmp_path):
    result = parse_trivy_report(get_fixture_path("trivy_non_secret.json"))

    assert result["findings_to_analyze"] == []


# -------------------------
# RUNNER TESTS (MOCK)
# -------------------------

@patch("subprocess.run")
def test_run_trivy_success(mock_run, tmp_path):
    output_file = tmp_path / "report.json"

    def fake_run(*args, **kwargs):
        output_file.write_text('{"Results": []}')
        return None

    mock_run.side_effect = fake_run

    error = run_trivy_scan("repo", str(output_file))

    assert error is None


@patch("subprocess.run")
def test_run_trivy_timeout(mock_run):
    mock_run.side_effect = subprocess.TimeoutExpired("cmd", 10)

    error = run_trivy_scan("repo", "out.json")

    assert "Timeout" in error["error"]


@patch("subprocess.run")
def test_run_trivy_failure(mock_run):
    mock_run.side_effect = subprocess.CalledProcessError(1, "cmd", stderr=b"fail")

    error = run_trivy_scan("repo", "out.json")

    assert "error" in error
    assert "details" in error


@patch("subprocess.run")
def test_run_trivy_no_file(mock_run):
    mock_run.return_value = None 

    error = run_trivy_scan("repo", "nonexistent.json")

    assert "error" in error

@patch("subprocess.run")
def test_run_trivy_empty_file(mock_run, tmp_path):
    output_file = tmp_path / "report.json"

    def fake_run(*args, **kwargs):
        output_file.write_text("")

    mock_run.side_effect = fake_run

    error = run_trivy_scan("repo", str(output_file))

    assert "error" in error

@patch("subprocess.run")
@patch("os.remove")
def test_run_trivy_removes_existing_file(mock_remove, mock_run, tmp_path):
    output_file = tmp_path / "report.json"

    output_file.write_text("old content")

    def fake_run(*args, **kwargs):
        output_file.write_text('{"Results": []}')

    mock_run.side_effect = fake_run

    error = run_trivy_scan("repo", str(output_file))

    assert error is None
    mock_remove.assert_called_once()


# -------------------------
# STRANDS TOOL TESTS
# -------------------------

@patch("src.agents.security.tools.trivy_functions.run_trivy_scan")
@patch("src.agents.security.tools.trivy_functions.parse_trivy_report")
def test_run_trivy_tool(mock_parse, mock_run):
    mock_run.return_value = None
    mock_parse.return_value = {"ok": True}

    result = run_trivy("repo")

    assert result["status"] == "success"


@patch("src.agents.security.tools.trivy_functions.run_trivy_scan")
def test_run_trivy_tool_error(mock_run):
    mock_run.return_value = {"error": "fail"}

    result = run_trivy("repo")

    assert result["status"] == "error"

@patch("src.agents.security.tools.trivy_functions.run_trivy_scan")
@patch("src.agents.security.tools.trivy_functions.parse_trivy_report")
def test_run_trivy_parser_error(mock_parse, mock_run):
    mock_run.return_value = None

    mock_parse.return_value = {
        "error": "Invalid JSON file generated by Trivy"
    }

    result = run_trivy("repo")

    assert result["status"] == "error"
    assert result["errors"][0]["type"] == "TrivyParseError"