import { GitHubAnalysis } from '../../../src/domain/entities/github-analysis.entity';
import { UserId } from '../../../src/domain/value-objects/user-id.vo';
import { RepoURL } from '../../../src/domain/value-objects/repo-url.vo';
import { BranchName } from '../../../src/domain/value-objects/branch-name.vo';
import { CommitHash } from '../../../src/domain/value-objects/commit-hash.vo';
import { v7 as uuid } from 'uuid';
import { AnalysisId } from '../../../src/domain/value-objects/analysis-id.vo';

describe('GitHubAnalysis Entity', () => {
  const makeValidAnalysis = (commit?: CommitHash) => {
    return GitHubAnalysis.create(
      AnalysisId.create(uuid()),
      UserId.create(uuid()),
      RepoURL.create('https://github.com/Suerto/QtLibrary.git'),
      BranchName.create('develop'),
      commit,
    );
  };

  describe('create()', () => {
    it('should create a valid GitHubAnalysis instance without commit', () => {
      const analysis = makeValidAnalysis();
      expect(analysis).toBeInstanceOf(GitHubAnalysis);
      expect(analysis.getCommit()).toBeNull();
    });

    it('should create a valid GitHubAnalysis instance with commit', () => {
      const commit = CommitHash.create('a'.repeat(40));
      const analysis = makeValidAnalysis(commit);
      expect(analysis.getCommit()).toBe(commit);
    });
  });

  describe('getters', () => {
    it('should return the correct repoURL', () => {
      const repoUrl = RepoURL.create('https://github.com/org/repo');
      const analysis = GitHubAnalysis.create(
        AnalysisId.create(uuid()),
        UserId.create(uuid()),
        repoUrl,
        BranchName.create('main'),
      );
      expect(analysis.getRepoURL()).toBe(repoUrl);
    });

    it('should return the correct branch', () => {
      const branch = BranchName.create('main');
      const analysis = GitHubAnalysis.create(
        AnalysisId.create(uuid()),
        UserId.create(uuid()),
        RepoURL.create('https://github.com/org/repo'),
        branch,
      );
      expect(analysis.getBranch()).toBe(branch);
    });

    it('should return an AnalysisId automatically generated by the base class', () => {
      const analysis = makeValidAnalysis();
      expect(analysis.getAnalysisId()).toBeDefined();
    });
  });

  describe('equals()', () => {
    it('should consider the same instance as equal', () => {
      const analysis = makeValidAnalysis();
      expect(analysis.equals(analysis)).toBe(true);
    });

    it('should consider two different instances as not equal (different IDs)', () => {
      const a1 = makeValidAnalysis();
      const a2 = makeValidAnalysis();
      expect(a1.equals(a2)).toBe(false);
    });

    it('should return false when comparing with null or different types', () => {
      const analysis = makeValidAnalysis();
      expect(analysis.equals(null as unknown as GitHubAnalysis)).toBe(false);
      expect(analysis.equals({} as unknown as GitHubAnalysis)).toBe(false);
    });
  });
});
